huge refactor

diff --git a/build/kazoo-tool b/build/kazoo-tool
--- a/build/kazoo-tool
+++ b/build/kazoo-tool
@@ -14,36 +14,29 @@ ERTS_LIB_DIR=$HOME/lib
 : ${ERLANG_COOKIE:=insecure-cookie}
 
 
-function log 
-{
+function log {
     local msg="$1"
-    echo -e "\E[36m[*]\E[0m ${msg}" 
+    echo -e "\E[36m[*]\E[0m ${msg}"
 }
 
-function errlog
-{
+function errlog {
     local msg="$1"
-    echo -e "\E[31m[*]\E[0m error: ${msg}" >&2 
+    echo -e "\E[31m[*]\E[0m error: ${msg}" >&2
 }
 
-
-function ping
-{
+function ping {
     $ERTS_PATH/bin/escript $HOME/bin/nodetool -name $LONG_NAME -setcookie $ERLANG_COOKIE ping
 }
 
-function remote_console
-{   
-    if ping > /dev/null
-    then
+function remote_console {
+    if ping > /dev/null; then
         local rem_name="remsh$(date +%s)-$LONG_NAME"
         local ntt=$($ERTS_PATH/bin/escript $HOME/bin/nodetool -name $LONG_NAME -setcookie $ERLANG_COOKIE rpcterms net_kernel get_net_ticktime)
         exec $ERTS_PATH/bin/erl -name $rem_name -remsh $LONG_NAME -boot $HOME/bin/start_clean -setcookie $ERLANG_COOKIE -hidden -kernel net_ticktime $ntt
     fi
 }
 
-function upgrade
-{
+function upgrade {
     local file=$1
     local package="${file%%.tar.gz}"
     [[ ! -f $file ]] && errlog "No file @ $file" && return 1
@@ -51,43 +44,34 @@ function upgrade
     ping && exec $ERTS_PATH/bin/escript $HOME/bin/install_upgrade.escript install kazoo -name $LONG_NAME $ERLANG_COOKIE "$package"
 }
 
-function escript
-{
+function escript {
     local script="$1"
     [[ ! -f $script ]] && errlog "No file @ $script" && return 1
     ping && exec $ERTS_PATH/bin/escript "$script"
 }
 
-function rpc
-{
+function rpc {
     local args="$@"
     [[ -z $args ]] && errlog "${FUNCNAME}: Usage: $0 $FUNCNAME Module Func Args" && return 1
     ping && exec $ERTS_PATH/bin/escript $HOME/bin/nodetool -name $LONG_NAME -setcookie $ERLANG_COOKIE rpc $@
 }
 
 # kazootool rpcterms kazoo_maintenance etop
-function rpcterms
-{
+function rpcterms {
     local args="$@"
     [[ -z $args ]] && errlog "${FUNCNAME}: Usage: $0 $FUNCNAME Module Func Args" && return 1
     ping && exec $ERTS_PATH/bin/escript $HOME/bin/nodetool -name $LONG_NAME -setcookie $ERLANG_COOKIE rpcterms $@
 }
 
 # kazootool eval 'kazoo_maintenance:etop()'
-function eval
-{
+function eval {
     local args="$@"
     [[ -z $args ]] && errlog "${FUNCNAME}: Usage: $0 $FUNCNAME Module Func Args" && return 1
     ping && exec $ERTS_PATH/bin/escript $HOME/bin/nodetool -name $LONG_NAME -setcookie $ERLANG_COOKIE eval $@
 }
 
-# function sup
-# {
 
-# }
-
-if [[ $1 ]]
-then
+if [[ $1 ]]; then
     "$@"
 else
     echo "usage: $(basename $0) {ping|remote_console|upgrade <package-base-name>|escript <escript-path>|rpc <args>|rpcterms <args>|eval <args>}"
